export const CHANGE_REGISTER_USERNAME = 'CHANGE_REGISTER_USERNAME';
export const CHANGE_REGISTER_PASSWORD = 'CHANGE_REGISTER_PASSWORD';
export const CHANGE_EMAIL_FIELD = 'CHANGE_EMAIL_FIELD';
export const CHANGE_SECOND_PASSWORD_FIELD = 'CHANGE_SECOND_PASSWORD_FIELD';

export const REGISTER_PENDING = 'REGISTER_PENDING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';