export const MYCHATS_PENDING = 'MYCHATS_PENDING';
export const MYCHATS_SUCCESS = 'MYCHATS_SUCCESS';
export const MYCHATS_FAILED = 'MYCHATS_FAILED';

export const CHANGE_HOME_VIEW = 'CHANGE_HOME_VIEW';