export const CHANGE_VIEW = 'CHANGE_VIEW';
export const LOGOUT = 'LOGOUT';
export const CHANGE_MODAL_VIEW = 'CHANGE_MODAL_VIEW';

// Login
export const CHANGE_LOGIN_DATA = 'CHANGE_LOGIN_DATA';
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

// Register
export const CHANGE_REGISTER_DATA = 'CHANGE_REGISTER_DATA';

export const REGISTER_PENDING = 'REGISTER_PENDING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';

// Conversations
export const MYCHATS_PENDING = 'MYCHATS_PENDING';
export const MYCHATS_SUCCESS = 'MYCHATS_SUCCESS';
export const MYCHATS_FAILED = 'MYCHATS_FAILED';

export const CHANGE_CURRENT_CHAT = 'CHANGE_CURRENT_CHAT';
export const TOGGLE_MENU_STATUS = 'CHANGE_MENU_STATUS';

export const CREATE_CHAT_PENDING = 'CREATE_CHAT_PENDING';
export const CREATE_CHAT_FAILED = 'CREATE_CHAT_FAILED';
export const CREATE_CHAT_SUCCESS = 'CREATE_CHAT_SUCCESS';

// Messages


// Users